# Generated by Django 5.1.6 on 2025-03-26 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_phone_number_profile_phone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="avg_work_hours",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="best_work_time",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.AddField(
            model_name="profile",
            name="activities",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="education",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="experience",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="habit_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="pomodoro_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="portfolio",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="projects_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="tagline",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="total_tasks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="task_completion_rate",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
