# Generated by Django 5.1.6 on 2025-03-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_profile_avg_work_hours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="activities",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="education",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="experience",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="portfolio",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="skills",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
