# Generated by Django 5.1.6 on 2025-03-29 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_profile_portfolio_education_experience_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="activities",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="education",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="skills",
        ),
    ]
