# Generated by Django 5.1.6 on 2025-03-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_profile_activities_remove_profile_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="field",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="experience",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="level",
            field=models.CharField(
                choices=[
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Expert", "Expert"),
                ],
                default="Beginner",
                max_length=50,
            ),
        ),
    ]
