# Generated by Django 5.1.6 on 2025-03-29 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_education_description_education_field_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="education",
            old_name="school",
            new_name="institution",
        ),
        migrations.RenameField(
            model_name="experience",
            old_name="position",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="education",
            name="end_year",
        ),
        migrations.RemoveField(
            model_name="education",
            name="start_year",
        ),
        migrations.AddField(
            model_name="education",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="experience",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="technologies",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[("technical", "Technical"), ("soft", "Soft")],
                default="technical",
                max_length=20,
            ),
        ),
    ]
