# Generated by Django 5.1.6 on 2025-03-30 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_school_education_institution_and_more"),
        ("api", "make_username_unique"),
    ]

    operations = []
